-- ================================================================
-- RIDEFLOW DATABASE SCHEMA (ORACLE EDITION) - UPDATED
-- Complete Oracle PL/SQL schema supporting all modules
-- Includes missing columns required by backend models
-- ================================================================

-- ================================================================
-- 1. USERS TABLE
-- ================================================================
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    phone_number VARCHAR2(20) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    account_status VARCHAR2(20) DEFAULT 'Active',
    profile_photo VARCHAR2(500),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT check_role CHECK (role IN ('Admin', 'Rider', 'Driver')),
    CONSTRAINT check_account_status CHECK (account_status IN ('Active', 'Suspended', 'Banned'))
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

CREATE OR REPLACE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 2. DRIVERS TABLE
-- ================================================================
CREATE TABLE drivers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL UNIQUE,
    license_number VARCHAR2(50) NOT NULL UNIQUE,
    cnic VARCHAR2(50) NOT NULL UNIQUE,
    license_expiry DATE,
    verification_status VARCHAR2(20) DEFAULT 'Pending',
    availability_status VARCHAR2(20) DEFAULT 'Offline',
    current_location_lat NUMBER(10, 8),
    current_location_lng NUMBER(11, 8),
    total_trips_completed NUMBER DEFAULT 0,
    average_rating NUMBER(3, 2) DEFAULT 0.00,
    is_flagged NUMBER(1) DEFAULT 0,
    flagged_reason VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT check_driver_verification CHECK (verification_status IN ('Pending', 'Verified', 'Rejected')),
    CONSTRAINT check_driver_availability CHECK (availability_status IN ('Online', 'Offline', 'On Trip')),
    CONSTRAINT check_driver_rating CHECK (average_rating >= 0 AND average_rating <= 5)
);

CREATE OR REPLACE TRIGGER trg_drivers_updated_at
BEFORE UPDATE ON drivers
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 3. LOCATIONS TABLE
-- ================================================================
CREATE TABLE locations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR2(100) NOT NULL,
    area VARCHAR2(100),
    address VARCHAR2(500) NOT NULL,
    latitude NUMBER(10, 8) NOT NULL,
    longitude NUMBER(11, 8) NOT NULL,
    type VARCHAR2(20) DEFAULT 'Other',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT check_location_type CHECK (type IN ('Residential', 'Commercial', 'Airport', 'Other'))
);

CREATE INDEX idx_loc_coords ON locations(latitude, longitude);

-- ================================================================
-- 4. VEHICLES TABLE
-- ================================================================
CREATE TABLE vehicles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id NUMBER NOT NULL,
    make VARCHAR2(100) NOT NULL,
    model VARCHAR2(100) NOT NULL,
    year NUMBER NOT NULL,
    color VARCHAR2(50),
    license_plate VARCHAR2(50) NOT NULL UNIQUE,
    vehicle_type VARCHAR2(20) NOT NULL,
    verification_status VARCHAR2(20) DEFAULT 'Pending',
    registration_number VARCHAR2(50),
    insurance_expiry DATE,
    fuel_type VARCHAR2(20) DEFAULT 'Petrol',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE,
    CONSTRAINT check_vehicle_type CHECK (vehicle_type IN ('Economy', 'Premium', 'Bike')),
    CONSTRAINT check_vehicle_verification CHECK (verification_status IN ('Pending', 'Verified', 'Rejected')),
    CONSTRAINT check_fuel_type CHECK (fuel_type IN ('Petrol', 'Diesel', 'Electric', 'Hybrid'))
);

CREATE OR REPLACE TRIGGER trg_vehicles_updated_at
BEFORE UPDATE ON vehicles
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 5. RIDES TABLE
-- ================================================================
CREATE TABLE rides (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id NUMBER NOT NULL,
    driver_id NUMBER,
    vehicle_id NUMBER,
    pickup_location_id NUMBER NOT NULL,
    dropoff_location_id NUMBER NOT NULL,
    status VARCHAR2(30) DEFAULT 'Requested',
    ride_type VARCHAR2(50) DEFAULT 'Regular', -- Required by model
    scheduled_time TIMESTAMP,
    accepted_time TIMESTAMP, -- Required by model logic
    pickup_time TIMESTAMP,
    dropoff_time TIMESTAMP,
    distance_km NUMBER(8, 2), -- From schema
    actual_distance NUMBER(8, 2), -- Required by model
    estimated_distance NUMBER(8, 2), -- Required by model
    duration_minutes NUMBER,
    base_fare NUMBER(10, 2), -- From schema
    estimated_fare NUMBER(10, 2), -- Required by model
    final_fare NUMBER(10, 2), -- From schema
    final_amount NUMBER(10, 2), -- Required by model
    per_km_charge NUMBER(8, 2),
    duration_charge NUMBER(8, 2),
    surge_multiplier NUMBER(3, 2) DEFAULT 1.00,
    subtotal NUMBER(10, 2),
    promo_discount NUMBER(10, 2) DEFAULT 0.00,
    payment_method VARCHAR2(20) DEFAULT 'Cash',
    payment_status VARCHAR2(20) DEFAULT 'Pending',
    cancellation_reason VARCHAR2(500),
    cancelled_by VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
    FOREIGN KEY (pickup_location_id) REFERENCES locations(id),
    FOREIGN KEY (dropoff_location_id) REFERENCES locations(id),
    
    CONSTRAINT check_ride_status CHECK (status IN ('Requested', 'Accepted', 'Driver En Route', 'In Progress', 'Started', 'Completed', 'Cancelled')),
    CONSTRAINT check_ride_pay_method CHECK (payment_method IN ('Cash', 'Wallet', 'Card')),
    CONSTRAINT check_ride_pay_status CHECK (payment_status IN ('Pending', 'Paid', 'Failed', 'Refunded')),
    CONSTRAINT check_cancelled_by CHECK (cancelled_by IN ('Rider', 'Driver', 'Admin'))
);

CREATE OR REPLACE TRIGGER trg_rides_updated_at
BEFORE UPDATE ON rides
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 6. PAYMENTS TABLE
-- ================================================================
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id NUMBER NOT NULL UNIQUE,
    rider_id NUMBER NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    payment_method VARCHAR2(20) NOT NULL,
    payment_status VARCHAR2(20) DEFAULT 'Pending',
    transaction_id VARCHAR2(100),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    promo_code_id NUMBER,
    promo_discount NUMBER(10, 2) DEFAULT 0.00,
    refund_reason VARCHAR2(500),
    refund_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ride_id) REFERENCES rides(id) ON DELETE CASCADE,
    FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE CASCADE,
    
    CONSTRAINT check_pay_method CHECK (payment_method IN ('Cash', 'Wallet', 'Card')),
    CONSTRAINT check_pay_status CHECK (payment_status IN ('Pending', 'Paid', 'Failed', 'Refunded'))
);

CREATE OR REPLACE TRIGGER trg_payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 7. RATINGS TABLE
-- ================================================================
CREATE TABLE ratings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id NUMBER NOT NULL,
    rated_by VARCHAR2(20) NOT NULL,
    rated_user_id NUMBER NOT NULL,
    score NUMBER NOT NULL,
    comment_text CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ride_id) REFERENCES rides(id) ON DELETE CASCADE,
    FOREIGN KEY (rated_user_id) REFERENCES users(id) ON DELETE CASCADE,
    
    CONSTRAINT check_rated_by CHECK (rated_by IN ('Rider', 'Driver')),
    CONSTRAINT check_rating_score CHECK (score >= 1 AND score <= 5)
);

CREATE OR REPLACE TRIGGER trg_ratings_updated_at
BEFORE UPDATE ON ratings
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 8. COMPLAINTS TABLE
-- ================================================================
CREATE TABLE complaints (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id NUMBER NOT NULL,
    filed_by NUMBER NOT NULL,
    complaint_type VARCHAR2(100) NOT NULL,
    description CLOB NOT NULL,
    status VARCHAR2(20) DEFAULT 'Open',
    resolution_notes CLOB,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    assigned_to NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ride_id) REFERENCES rides(id) ON DELETE CASCADE,
    FOREIGN KEY (filed_by) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    
    CONSTRAINT check_complaint_status CHECK (status IN ('Open', 'In Review', 'Resolved', 'Dismissed'))
);

CREATE OR REPLACE TRIGGER trg_complaints_updated_at
BEFORE UPDATE ON complaints
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 9. PROMO_CODES TABLE
-- ================================================================
CREATE TABLE promo_codes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(50) NOT NULL UNIQUE,
    discount_type VARCHAR2(20) DEFAULT 'Percent',
    discount_value NUMBER(10, 2) NOT NULL,
    min_ride_fare NUMBER(10, 2) DEFAULT 0.00,
    max_discount NUMBER(10, 2),
    expiry_date DATE NOT NULL,
    is_active NUMBER(1) DEFAULT 1,
    max_uses NUMBER,
    used_count NUMBER DEFAULT 0,
    applicable_to VARCHAR2(20) DEFAULT 'All',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT check_promo_type CHECK (discount_type IN ('Percent', 'Fixed')),
    CONSTRAINT check_promo_app CHECK (applicable_to IN ('All', 'Rider', 'Driver'))
);

-- ================================================================
-- 10. FARE_RULES TABLE
-- ================================================================
CREATE TABLE fare_rules (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type VARCHAR2(20) NOT NULL UNIQUE,
    base_rate NUMBER(10, 2) NOT NULL,
    per_km_rate NUMBER(8, 2) NOT NULL,
    per_minute_rate NUMBER(8, 2) NOT NULL,
    surge_multiplier NUMBER(3, 2) DEFAULT 1.5,
    is_peak_hour NUMBER(1) DEFAULT 0,
    peak_hours_start INTERVAL DAY TO SECOND,
    peak_hours_end INTERVAL DAY TO SECOND,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT check_fare_vtype CHECK (vehicle_type IN ('Economy', 'Premium', 'Bike'))
);

CREATE OR REPLACE TRIGGER trg_fare_rules_updated_at
BEFORE UPDATE ON fare_rules
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 11. DRIVER_EARNINGS TABLE
-- ================================================================
CREATE TABLE driver_earnings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id NUMBER NOT NULL,
    ride_id NUMBER NOT NULL,
    gross_fare NUMBER(10, 2) NOT NULL,
    commission_percent NUMBER(5, 2) NOT NULL,
    commission_amount NUMBER(10, 2) NOT NULL,
    net_earning NUMBER(10, 2) NOT NULL,
    payout_status VARCHAR2(20) DEFAULT 'Pending',
    payout_date TIMESTAMP,
    payout_method VARCHAR2(30) DEFAULT 'Bank Transfer',
    bank_account VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE,
    FOREIGN KEY (ride_id) REFERENCES rides(id) ON DELETE CASCADE,
    
    CONSTRAINT check_payout_status CHECK (payout_status IN ('Pending', 'Processed', 'Cancelled')),
    CONSTRAINT check_payout_method CHECK (payout_method IN ('Bank Transfer', 'Wallet', 'Check'))
);

CREATE OR REPLACE TRIGGER trg_earnings_updated_at
BEFORE UPDATE ON driver_earnings
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ================================================================
-- 12. WALLET_TRANSACTIONS TABLE
-- ================================================================
CREATE TABLE wallet_transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id NUMBER NOT NULL,
    type VARCHAR2(20) NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    balance_after NUMBER(10, 2) NOT NULL,
    ride_id NUMBER,
    promo_code_id NUMBER,
    description VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (ride_id) REFERENCES rides(id) ON DELETE SET NULL,
    FOREIGN KEY (promo_code_id) REFERENCES promo_codes(id) ON DELETE SET NULL,
    
    CONSTRAINT check_wallet_type CHECK (type IN ('TopUp', 'RidePayment', 'Refund', 'PromoCredit', 'Withdrawal'))
);

-- ================================================================
-- 13. RIDE_HISTORY TABLE
-- ================================================================
CREATE TABLE ride_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id NUMBER NOT NULL UNIQUE,
    rider_id NUMBER NOT NULL,
    driver_id NUMBER,
    vehicle_id NUMBER,
    pickup_location_id NUMBER NOT NULL,
    dropoff_location_id NUMBER NOT NULL,
    ride_status VARCHAR2(20) NOT NULL,
    fare NUMBER(10, 2),
    distance_km NUMBER(8, 2),
    duration_minutes NUMBER,
    archived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ride_id) REFERENCES rides(id) ON DELETE CASCADE,
    FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
    FOREIGN KEY (pickup_location_id) REFERENCES locations(id),
    FOREIGN KEY (dropoff_location_id) REFERENCES locations(id),
    
    CONSTRAINT check_hist_status CHECK (ride_status IN ('Completed', 'Cancelled'))
);

-- ================================================================
-- TRIGGERS (BUSINESS LOGIC)
-- ================================================================

CREATE OR REPLACE TRIGGER trg_update_driver_rating
AFTER INSERT ON ratings
FOR EACH ROW
DECLARE
    v_driver_id NUMBER;
    v_avg_rating NUMBER(3, 2);
BEGIN
    BEGIN
        SELECT id INTO v_driver_id FROM drivers WHERE user_id = :NEW.rated_user_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN v_driver_id := NULL; END;
    
    IF v_driver_id IS NOT NULL THEN
        SELECT ROUND(AVG(score), 2) INTO v_avg_rating FROM ratings 
        WHERE rated_user_id = :NEW.rated_user_id AND rated_by = 'Rider';
        UPDATE drivers SET average_rating = COALESCE(v_avg_rating, 0) WHERE id = v_driver_id;
        IF v_avg_rating < 3.5 THEN
            UPDATE drivers SET is_flagged = 1, flagged_reason = 'Low average rating' WHERE id = v_driver_id;
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_archive_ride
AFTER UPDATE ON rides
FOR EACH ROW
BEGIN
    IF :NEW.status = 'Completed' AND :OLD.status != 'Completed' THEN
        INSERT INTO ride_history (ride_id, rider_id, driver_id, vehicle_id, pickup_location_id, dropoff_location_id, ride_status, fare, distance_km, duration_minutes)
        VALUES (:NEW.id, :NEW.rider_id, :NEW.driver_id, :NEW.vehicle_id, :NEW.pickup_location_id, :NEW.dropoff_location_id, 'Completed', COALESCE(:NEW.final_fare, :NEW.final_amount), COALESCE(:NEW.distance_km, :NEW.actual_distance), :NEW.duration_minutes);
    ELSIF :NEW.status = 'Cancelled' AND :OLD.status != 'Cancelled' THEN
        INSERT INTO ride_history (ride_id, rider_id, driver_id, vehicle_id, pickup_location_id, dropoff_location_id, ride_status, fare, distance_km, duration_minutes)
        VALUES (:NEW.id, :NEW.rider_id, :NEW.driver_id, :NEW.vehicle_id, :NEW.pickup_location_id, :NEW.dropoff_location_id, 'Cancelled', COALESCE(:NEW.final_fare, :NEW.final_amount), COALESCE(:NEW.distance_km, :NEW.actual_distance), :NEW.duration_minutes);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_update_driver_stats
AFTER UPDATE ON rides
FOR EACH ROW
BEGIN
    IF :NEW.status = 'Completed' AND :OLD.status != 'Completed' THEN
        UPDATE drivers SET total_trips_completed = total_trips_completed + 1, availability_status = 'Online' WHERE id = :NEW.driver_id;
    ELSIF :NEW.status = 'Cancelled' AND :OLD.status != 'Cancelled' AND :NEW.cancelled_by = 'Driver' THEN
        UPDATE drivers SET availability_status = 'Online' WHERE id = :NEW.driver_id;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_set_driver_on_trip
AFTER UPDATE ON rides
FOR EACH ROW
BEGIN
    IF :NEW.status IN ('Accepted', 'Driver En Route', 'In Progress') AND :OLD.status = 'Requested' THEN
        UPDATE drivers SET availability_status = 'On Trip' WHERE id = :NEW.driver_id;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_create_driver_earning
AFTER UPDATE ON rides
FOR EACH ROW
DECLARE v_commission_pct NUMBER(5,2) := 20.00;
BEGIN
    IF :NEW.status = 'Completed' AND :OLD.status != 'Completed' THEN
        INSERT INTO driver_earnings (driver_id, ride_id, gross_fare, commission_percent, commission_amount, net_earning)
        VALUES (:NEW.driver_id, :NEW.id, COALESCE(:NEW.final_fare, :NEW.final_amount), v_commission_pct, ROUND(COALESCE(:NEW.final_fare, :NEW.final_amount) * v_commission_pct / 100, 2), ROUND(COALESCE(:NEW.final_fare, :NEW.final_amount) * (100 - v_commission_pct) / 100, 2));
    END IF;
END;
/

-- ================================================================
-- PROCEDURES
-- ================================================================

CREATE OR REPLACE PROCEDURE calculate_fare(
    p_vehicle_type IN VARCHAR2, p_distance_km IN NUMBER, p_duration_minutes IN NUMBER, p_surge_multiplier IN NUMBER,
    p_base_fare OUT NUMBER, p_per_km_charge OUT NUMBER, p_duration_charge OUT NUMBER, p_subtotal OUT NUMBER, p_final_fare OUT NUMBER
) AS
    v_base_rate NUMBER(10, 2); v_per_km_rate NUMBER(8, 2); v_per_minute_rate NUMBER(8, 2);
BEGIN
    SELECT base_rate, per_km_rate, per_minute_rate INTO v_base_rate, v_per_km_rate, v_per_minute_rate FROM fare_rules WHERE vehicle_type = p_vehicle_type;
    p_base_fare := v_base_rate; p_per_km_charge := (p_distance_km * v_per_km_rate); p_duration_charge := (p_duration_minutes * v_per_minute_rate);
    p_subtotal := (p_base_fare + p_per_km_charge + p_duration_charge);
    p_final_fare := ROUND(p_subtotal * COALESCE(p_surge_multiplier, 1.0), 2);
END;
/

CREATE OR REPLACE PROCEDURE get_available_drivers(
    p_latitude IN NUMBER, p_longitude IN NUMBER, p_max_distance_km IN NUMBER, p_vehicle_type IN VARCHAR2, p_cursor OUT SYS_REFCURSOR
) AS v_pi NUMBER := 3.141592653589793;
BEGIN
    OPEN p_cursor FOR
    SELECT d.id, u.full_name, u.email, d.average_rating, d.current_location_lat, d.current_location_lng,
        (6371 * ACOS(COS(p_latitude * v_pi / 180) * COS(d.current_location_lat * v_pi / 180) * COS((d.current_location_lng * v_pi / 180) - (p_longitude * v_pi / 180)) + SIN(p_latitude * v_pi / 180) * SIN(d.current_location_lat * v_pi / 180))) AS distance_km
    FROM drivers d JOIN users u ON d.user_id = u.id JOIN vehicles v ON d.id = v.driver_id
    WHERE d.availability_status = 'Online' AND d.verification_status = 'Verified' AND v.verification_status = 'Verified' AND v.vehicle_type = p_vehicle_type AND d.is_flagged = 0
    AND (6371 * ACOS(COS(p_latitude * v_pi / 180) * COS(d.current_location_lat * v_pi / 180) * COS((d.current_location_lng * v_pi / 180) - (p_longitude * v_pi / 180)) + SIN(p_latitude * v_pi / 180) * SIN(d.current_location_lat * v_pi / 180))) <= p_max_distance_km
    ORDER BY d.average_rating DESC, distance_km ASC FETCH FIRST 10 ROWS ONLY;
END;
/

CREATE OR REPLACE PROCEDURE get_rider_wallet_balance(p_rider_id IN NUMBER, p_balance OUT NUMBER) AS
BEGIN
    SELECT COALESCE(SUM(CASE WHEN type IN ('TopUp', 'Refund', 'PromoCredit') THEN amount WHEN type IN ('RidePayment', 'Withdrawal') THEN -amount END), 0) INTO p_balance
    FROM wallet_transactions WHERE rider_id = p_rider_id;
END;
/

CREATE OR REPLACE PROCEDURE get_admin_platform_overview(p_total_users OUT NUMBER, p_total_drivers OUT NUMBER, p_total_rides OUT NUMBER, p_total_revenue OUT NUMBER, p_active_complaints OUT NUMBER) AS
BEGIN
    SELECT COUNT(*) INTO p_total_users FROM users;
    SELECT COUNT(*) INTO p_total_drivers FROM drivers;
    SELECT COUNT(*) INTO p_total_rides FROM rides;
    SELECT COALESCE(SUM(COALESCE(final_fare, final_amount)), 0) INTO p_total_revenue FROM rides WHERE status = 'Completed';
    SELECT COUNT(*) INTO p_active_complaints FROM complaints WHERE status IN ('Open', 'In Review');
END;
/

COMMIT;
